name: roberta-eval
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy=1.19.1
  - torch=1.6.0
  - tqdm=4.48.2
  - spacy=2.3.1
  - gensim=3.8.0
  - ftfy=5.8
  - nltk=3.5
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - pip:
    - transformers=3.0.2
